name: Blank workflow

on: [push]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run-script build-linux
    - uses: actions/upload-artifact@v2
      with:
        name: beta.linux
        path: ./dist/drop*
build-win:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run-script build-win
    - uses: actions/upload-artifact@v2
      with:
        name: beta.windows
        path: ./dist/drop*
